{% set name = "autode" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/duartegroup/autodE/archive/v{{ version }}.tar.gz
  sha256: 0a60b01658fe3e0d6263ed44c43d63d6788fa6a94eab063f005df042899c69bb

build:
  number: 4
  skip: True  # [py<37 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - rdkit
    - numpy
    - networkx 2.5.*
    - matplotlib-base
    - scipy

test:
  imports:
    - autode

about:
  home: https://github.com/duartegroup/autodE
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Automated reaction profile generation'
  description: |
    autodE is a Python package designed for the rapid generation of chemical
    reaction (free) energy profiles from SMILES or xyz geometries of reactants
    and products. It makes use of external electronic structure packages to
    perform geometry optimisations, single point energy and force evaluations.
  doc_url: https://duartegroup.github.io/autodE/
  dev_url: https://github.com/duartegroup/autodE/

extra:
  recipe-maintainers:
    - t-young31
