{% set name = "autode" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/duartegroup/autodE/archive/v{{ version }}.tar.gz
  sha256: 0ba77b80a18461fa67afe860ea3ad9bb2fc02e5147b5a26c3f2790f8d7c495bd

build:
  number: 0
  skip: True  # [py<36 or win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - rdkit
    - numpy
    - networkx
    - matplotlib-base
    - scipy

test:
  imports:
    - autode

about:
  home: https://github.com/duartegroup/autodE
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Automated reaction profile generation'
  description: |
    autodE is a Python package designed for the rapid generation of chemical
    reaction (free) energy profiles from SMILES or xyz geometries of reactants
    and products. It makes use of external electronic structure packages to
    perform geometry optimisations, single point energy and force evaluations.
  doc_url: https://duartegroup.github.io/autodE/
  dev_url: https://github.com/duartegroup/autodE/

extra:
  recipe-maintainers:
    - t-young31
