{% set name = "autode" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/duartegroup/autodE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d4b80c945015931738b8a41799e76be83a2453620279fd7025f3d95e32327e72

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - rdkit
    - numpy
    - networkx
    - matplotlib-base
    - scipy
    - loky

test:
  imports:
    - autode

about:
  home: https://github.com/duartegroup/autodE
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Automated reaction profile generation
  description: |
    autodE is a Python package designed for the rapid generation of chemical
    reaction (free) energy profiles from SMILES or xyz geometries of reactants
    and products. It makes use of external electronic structure packages to
    perform geometry optimisations, single point energy and force evaluations.
  doc_url: https://duartegroup.github.io/autodE/
  dev_url: https://github.com/duartegroup/autodE/

extra:
  recipe-maintainers:
    - t-young31
