{% set name = "autode" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/duartegroup/autodE/archive/v{{ version }}.tar.gz
  sha256: 65aa7a913eddb202ae12ebaafff1c5d9ba09a0a9ea698d321356ea7289d8eb8f

build:
  number: 0
  skip: True  # [py<37 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - rdkit
    - numpy
    - networkx 2.5.*
    - matplotlib-base
    - scipy

test:
  imports:
    - autode

about:
  home: https://github.com/duartegroup/autodE
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Automated reaction profile generation'
  description: |
    autodE is a Python package designed for the rapid generation of chemical
    reaction (free) energy profiles from SMILES or xyz geometries of reactants
    and products. It makes use of external electronic structure packages to
    perform geometry optimisations, single point energy and force evaluations.
  doc_url: https://duartegroup.github.io/autodE/
  dev_url: https://github.com/duartegroup/autodE/

extra:
  recipe-maintainers:
    - t-young31
